// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/Qi.proto

#include "proto/Qi.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = ::PROTOBUF_NAMESPACE_ID::internal;
namespace proto {
template <typename>
PROTOBUF_CONSTEXPR PQi::PQi(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.id_)*/ {}

  , /*decltype(_impl_.qi_)*/ {}

  , /*decltype(_impl_._cached_size_)*/{}} {}
struct PQiDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PQiDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PQiDefaultTypeInternal() {}
  union {
    PQi _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PQiDefaultTypeInternal _PQi_default_instance_;
}  // namespace proto
static ::_pb::Metadata file_level_metadata_proto_2fQi_2eproto[1];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_proto_2fQi_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_proto_2fQi_2eproto = nullptr;
const ::uint32_t TableStruct_proto_2fQi_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::proto::PQi, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::proto::PQi, _impl_.id_),
    PROTOBUF_FIELD_OFFSET(::proto::PQi, _impl_.qi_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        { 0, -1, -1, sizeof(::proto::PQi)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::proto::_PQi_default_instance_._instance,
};
const char descriptor_table_protodef_proto_2fQi_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\016proto/Qi.proto\022\005proto\"\035\n\003PQi\022\n\n\002id\030\001 \003"
    "(\005\022\n\n\002qi\030\002 \003(\005"
};
static ::absl::once_flag descriptor_table_proto_2fQi_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_proto_2fQi_2eproto = {
    false,
    false,
    54,
    descriptor_table_protodef_proto_2fQi_2eproto,
    "proto/Qi.proto",
    &descriptor_table_proto_2fQi_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_proto_2fQi_2eproto::offsets,
    file_level_metadata_proto_2fQi_2eproto,
    file_level_enum_descriptors_proto_2fQi_2eproto,
    file_level_service_descriptors_proto_2fQi_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_proto_2fQi_2eproto_getter() {
  return &descriptor_table_proto_2fQi_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_proto_2fQi_2eproto(&descriptor_table_proto_2fQi_2eproto);
namespace proto {
// ===================================================================

class PQi::_Internal {
 public:
};

PQi::PQi(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:proto.PQi)
}
PQi::PQi(const PQi& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PQi* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.id_) { from._impl_.id_ }

    , decltype(_impl_.qi_) { from._impl_.qi_ }

    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:proto.PQi)
}

inline void PQi::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_.id_) { arena }

    , decltype(_impl_.qi_) { arena }

    , /*decltype(_impl_._cached_size_)*/{}
  };
}

PQi::~PQi() {
  // @@protoc_insertion_point(destructor:proto.PQi)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PQi::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.id_.~RepeatedField();
  _impl_.qi_.~RepeatedField();
}

void PQi::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PQi::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.PQi)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_mutable_id()->Clear();
  _internal_mutable_qi()->Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PQi::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated int32 id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 8)) {
          ptr -= 1;
          do {
            ptr += 1;
            _internal_add_id(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr));
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<8>(ptr));
        } else if (static_cast<::uint8_t>(tag) == 10) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedInt32Parser(_internal_mutable_id(), ptr, ctx);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      // repeated int32 qi = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 16)) {
          ptr -= 1;
          do {
            ptr += 1;
            _internal_add_qi(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr));
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<16>(ptr));
        } else if (static_cast<::uint8_t>(tag) == 18) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedInt32Parser(_internal_mutable_qi(), ptr, ctx);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::uint8_t* PQi::_InternalSerialize(
    ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:proto.PQi)
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated int32 id = 1;
  for (int i = 0, n = this->_internal_id_size(); i < n; ++i) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(
        1, this->_internal_id(i), target);
  }

  // repeated int32 qi = 2;
  for (int i = 0, n = this->_internal_qi_size(); i < n; ++i) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(
        2, this->_internal_qi(i), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:proto.PQi)
  return target;
}

::size_t PQi::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:proto.PQi)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated int32 id = 1;
  {
    std::size_t data_size = ::_pbi::WireFormatLite::Int32Size(
        this->_internal_id())
    ;
    std::size_t tag_size = std::size_t{1} *
        ::_pbi::FromIntSize(this->_internal_id_size());
    ;
    total_size += tag_size + data_size;
  }

  // repeated int32 qi = 2;
  {
    std::size_t data_size = ::_pbi::WireFormatLite::Int32Size(
        this->_internal_qi())
    ;
    std::size_t tag_size = std::size_t{1} *
        ::_pbi::FromIntSize(this->_internal_qi_size());
    ;
    total_size += tag_size + data_size;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PQi::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PQi::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PQi::GetClassData() const { return &_class_data_; }


void PQi::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PQi*>(&to_msg);
  auto& from = static_cast<const PQi&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:proto.PQi)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.id_.MergeFrom(from._impl_.id_);
  _this->_impl_.qi_.MergeFrom(from._impl_.qi_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PQi::CopyFrom(const PQi& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:proto.PQi)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PQi::IsInitialized() const {
  return true;
}

void PQi::InternalSwap(PQi* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.id_.InternalSwap(&other->_impl_.id_);
  _impl_.qi_.InternalSwap(&other->_impl_.qi_);
}

::PROTOBUF_NAMESPACE_ID::Metadata PQi::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_proto_2fQi_2eproto_getter, &descriptor_table_proto_2fQi_2eproto_once,
      file_level_metadata_proto_2fQi_2eproto[0]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::proto::PQi*
Arena::CreateMaybeMessage< ::proto::PQi >(Arena* arena) {
  return Arena::CreateMessageInternal< ::proto::PQi >(arena);
}
PROTOBUF_NAMESPACE_CLOSE
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
