// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/Qi.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_proto_2fQi_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_proto_2fQi_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4023000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4023004 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/message.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_proto_2fQi_2eproto

PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_proto_2fQi_2eproto {
    static const ::uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable
    descriptor_table_proto_2fQi_2eproto;
namespace proto {
class PQi;
struct PQiDefaultTypeInternal;
extern PQiDefaultTypeInternal _PQi_default_instance_;
}  // namespace proto
PROTOBUF_NAMESPACE_OPEN
template <>
::proto::PQi* Arena::CreateMaybeMessage<::proto::PQi>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

namespace proto {

// ===================================================================

// -------------------------------------------------------------------

class PQi final
    : public ::PROTOBUF_NAMESPACE_ID::
          Message /* @@protoc_insertion_point(class_definition:proto.PQi) */ {
   public:
    inline PQi() : PQi(nullptr) {}
    ~PQi() override;
    template <typename = void>
    explicit PROTOBUF_CONSTEXPR PQi(
        ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

    PQi(const PQi& from);
    PQi(PQi&& from) noexcept : PQi() { *this = ::std::move(from); }

    inline PQi& operator=(const PQi& from) {
        CopyFrom(from);
        return *this;
    }
    inline PQi& operator=(PQi&& from) noexcept {
        if (this == &from) return *this;
        if (GetOwningArena() == from.GetOwningArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
            && GetOwningArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
        ) {
            InternalSwap(&from);
        } else {
            CopyFrom(from);
        }
        return *this;
    }

    inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields()
        const {
        return _internal_metadata_
            .unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(
                ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
    }
    inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
        return _internal_metadata_
            .mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
    }

    static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
        return GetDescriptor();
    }
    static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
        return default_instance().GetMetadata().descriptor;
    }
    static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
        return default_instance().GetMetadata().reflection;
    }
    static const PQi& default_instance() {
        return *internal_default_instance();
    }
    static inline const PQi* internal_default_instance() {
        return reinterpret_cast<const PQi*>(&_PQi_default_instance_);
    }
    static constexpr int kIndexInFileMessages = 0;

    friend void swap(PQi& a, PQi& b) { a.Swap(&b); }
    inline void Swap(PQi* other) {
        if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
        if (GetOwningArena() != nullptr &&
            GetOwningArena() == other->GetOwningArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
        if (GetOwningArena() == other->GetOwningArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
            InternalSwap(other);
        } else {
            ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
        }
    }
    void UnsafeArenaSwap(PQi* other) {
        if (other == this) return;
        ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
        InternalSwap(other);
    }

    // implements Message ----------------------------------------------

    PQi* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
        return CreateMaybeMessage<PQi>(arena);
    }
    using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
    void CopyFrom(const PQi& from);
    using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
    void MergeFrom(const PQi& from) { PQi::MergeImpl(*this, from); }

   private:
    static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg,
                          const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);

   public:
    PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
    bool IsInitialized() const final;

    ::size_t ByteSizeLong() const final;
    const char* _InternalParse(
        const char* ptr,
        ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
    ::uint8_t* _InternalSerialize(
        ::uint8_t* target,
        ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
    int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

   private:
    void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
    void SharedDtor();
    void SetCachedSize(int size) const final;
    void InternalSwap(PQi* other);

   private:
    friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
    static ::absl::string_view FullMessageName() { return "proto.PQi"; }

   protected:
    explicit PQi(::PROTOBUF_NAMESPACE_ID::Arena* arena);

   public:
    static const ClassData _class_data_;
    const ::PROTOBUF_NAMESPACE_ID::Message::ClassData* GetClassData()
        const final;

    ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

    // nested types ----------------------------------------------------

    // accessors -------------------------------------------------------

    enum : int {
        kIdFieldNumber = 1,
        kQiFieldNumber = 2,
    };
    // repeated int32 id = 1;
    int id_size() const;

   private:
    int _internal_id_size() const;

   public:
    void clear_id();
    ::int32_t id(int index) const;
    void set_id(int index, ::int32_t value);
    void add_id(::int32_t value);
    const ::PROTOBUF_NAMESPACE_ID::RepeatedField<::int32_t>& id() const;
    ::PROTOBUF_NAMESPACE_ID::RepeatedField<::int32_t>* mutable_id();

   private:
    ::int32_t _internal_id(int index) const;
    void _internal_add_id(::int32_t value);
    const ::PROTOBUF_NAMESPACE_ID::RepeatedField<::int32_t>& _internal_id()
        const;
    ::PROTOBUF_NAMESPACE_ID::RepeatedField<::int32_t>* _internal_mutable_id();

   public:
    // repeated int32 qi = 2;
    int qi_size() const;

   private:
    int _internal_qi_size() const;

   public:
    void clear_qi();
    ::int32_t qi(int index) const;
    void set_qi(int index, ::int32_t value);
    void add_qi(::int32_t value);
    const ::PROTOBUF_NAMESPACE_ID::RepeatedField<::int32_t>& qi() const;
    ::PROTOBUF_NAMESPACE_ID::RepeatedField<::int32_t>* mutable_qi();

   private:
    ::int32_t _internal_qi(int index) const;
    void _internal_add_qi(::int32_t value);
    const ::PROTOBUF_NAMESPACE_ID::RepeatedField<::int32_t>& _internal_qi()
        const;
    ::PROTOBUF_NAMESPACE_ID::RepeatedField<::int32_t>* _internal_mutable_qi();

   public:
    // @@protoc_insertion_point(class_scope:proto.PQi)
   private:
    class _Internal;

    template <typename T>
    friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
    typedef void InternalArenaConstructable_;
    typedef void DestructorSkippable_;
    struct Impl_ {
        ::PROTOBUF_NAMESPACE_ID::RepeatedField<::int32_t> id_;
        ::PROTOBUF_NAMESPACE_ID::RepeatedField<::int32_t> qi_;
        mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    };
    union {
        Impl_ _impl_;
    };
    friend struct ::TableStruct_proto_2fQi_2eproto;
};

// ===================================================================

// ===================================================================

#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// PQi

// repeated int32 id = 1;
inline int PQi::_internal_id_size() const { return _impl_.id_.size(); }
inline int PQi::id_size() const { return _internal_id_size(); }
inline void PQi::clear_id() { _internal_mutable_id()->Clear(); }
inline ::int32_t PQi::id(int index) const {
    // @@protoc_insertion_point(field_get:proto.PQi.id)
    return _internal_id(index);
}
inline void PQi::set_id(int index, ::int32_t value) {
    _internal_mutable_id()->Set(index, value);
    // @@protoc_insertion_point(field_set:proto.PQi.id)
}
inline void PQi::add_id(::int32_t value) {
    _internal_add_id(value);
    // @@protoc_insertion_point(field_add:proto.PQi.id)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField<::int32_t>& PQi::id()
    const {
    // @@protoc_insertion_point(field_list:proto.PQi.id)
    return _internal_id();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField<::int32_t>* PQi::mutable_id() {
    // @@protoc_insertion_point(field_mutable_list:proto.PQi.id)
    return _internal_mutable_id();
}

inline ::int32_t PQi::_internal_id(int index) const {
    return _internal_id().Get(index);
}
inline void PQi::_internal_add_id(::int32_t value) {
    _internal_mutable_id()->Add(value);
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField<::int32_t>&
PQi::_internal_id() const {
    return _impl_.id_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField<::int32_t>*
PQi::_internal_mutable_id() {
    return &_impl_.id_;
}

// repeated int32 qi = 2;
inline int PQi::_internal_qi_size() const { return _impl_.qi_.size(); }
inline int PQi::qi_size() const { return _internal_qi_size(); }
inline void PQi::clear_qi() { _internal_mutable_qi()->Clear(); }
inline ::int32_t PQi::qi(int index) const {
    // @@protoc_insertion_point(field_get:proto.PQi.qi)
    return _internal_qi(index);
}
inline void PQi::set_qi(int index, ::int32_t value) {
    _internal_mutable_qi()->Set(index, value);
    // @@protoc_insertion_point(field_set:proto.PQi.qi)
}
inline void PQi::add_qi(::int32_t value) {
    _internal_add_qi(value);
    // @@protoc_insertion_point(field_add:proto.PQi.qi)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField<::int32_t>& PQi::qi()
    const {
    // @@protoc_insertion_point(field_list:proto.PQi.qi)
    return _internal_qi();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField<::int32_t>* PQi::mutable_qi() {
    // @@protoc_insertion_point(field_mutable_list:proto.PQi.qi)
    return _internal_mutable_qi();
}

inline ::int32_t PQi::_internal_qi(int index) const {
    return _internal_qi().Get(index);
}
inline void PQi::_internal_add_qi(::int32_t value) {
    _internal_mutable_qi()->Add(value);
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField<::int32_t>&
PQi::_internal_qi() const {
    return _impl_.qi_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField<::int32_t>*
PQi::_internal_mutable_qi() {
    return &_impl_.qi_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace proto

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_proto_2fQi_2eproto_2epb_2eh
