name: Clang Format
on:
    workflow_call:
      inputs:
        event_name:
          required: true
          type: string

permissions:
    actions: read
    checks: read
    contents: write
jobs:
    clang-format:
        name: C++ 代码格式化 (clang-format)
        runs-on: ubuntu-latest
        if: ${{ inputs.event_name != 'pull_request' }}
        steps:
          - name: 检测版本
            run: |
                clang-format --version
          - name: 下载分支
            uses: actions/checkout@v3
          - name: 获取当前分支
            run: |
                echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >>$GITHUB_OUTPUT
            id: extract_branch
          - name: 运行格式化程序
            run: |
                bash ./.github/scripts/run_clang_format.sh
          - name: 输出更改
            run: |
                git diff --color
          - name: 提交更改并推送
            uses: Andro999b/push@v1.3
            with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                message: "[skip cl] (Bot) 格式化代码 (C++) 于提交 ${{ github.sha }} (${{ steps.extract_branch.outputs.branch }})"
                branch: ${{ steps.extract_branch.outputs.branch }}
          - name: 上传 Log
            if: always()
            uses: actions/upload-artifact@v3.1.2
            with:
                name: clang-format-run
                path:
                    ./clang-format
    need-format:
        name: 代码需要格式化
        runs-on: ubuntu-latest
        if: ${{ inputs.event_name == 'pull_request' }}
        steps:
          - name: 本代码需要格式化 (Pull Request)
            run: |
              exit 1