name: Clang Format
on:
    workflow_call:
jobs:
    clang-format:
        name: C++ 代码格式化 (clang-format)
        runs-on: ubuntu-latest
        steps:
          - name: 检测版本
            run: |
                clang-format --version
          - name: 下载分支
            uses: actions/checkout@v3
            with:
                fetch-depth: 3
          - name: 运行格式化程序
            run: |
                bash ./.github/scripts/run_clang_format.sh
          - name: 上传 Log
            if: always()
            uses: actions/upload-artifact@v3.1.2
            with:
                name: clang-format-run
                path:
                    .github/scripts/clang-format