name: CMake Matrix Self Hosted

on:
  # push:
  #   branches: [ "master" , "dev" ]
  # pull_request:
  #   branches: [ "master" , "dev" ]
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    defaults:
      run:
        shell: cmd
    strategy:
      fail-fast: false
      matrix:
        profile: [ MinGW Makefiles ]
        build_type: [ Release ]
        gbk: [ off , on ]

    name: "Build"
    runs-on: [softer-server]
    steps:
    - name: 输出 CMake 支持 Generators
      run: |
        cmake --help
    - name: 下载分支
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - name: 配置 CMake
      run: cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DGBK=${{ matrix.gbk }} -G "${{ matrix.profile }}"
    - name: 编译
      run: cmake --build ${{github.workspace}}/build --config "${{ matrix.build_type }}" --target=wooden_game -j 32
