name: CMake Test (Unix)
on:
    workflow_call:
jobs:
    build:
        strategy:
          fail-fast: false
          matrix:
              os: [ ubuntu-latest, macos-13 ]
              profile: [ Unix Makefiles ]
              build_type: [ Debug ]
        name: "Unit Test"
        runs-on: ${{ matrix.os }}
        steps:
          - name: 探测版本
            run: |
                echo "G++ version"
                echo "::group::g++ version"
                g++ --version
                echo "::endgroup::"

                echo "GCC version"
                echo "::group::gcc version"
                gcc --version
                echo "::endgroup::"

                echo "Make version"
                echo "::group::Make version"
                make --version
                echo "::endgroup::"

                echo "CMake version"
                echo "::group::CMake Version"
                cmake --version
                echo "::endgroup::"

                echo "python version"
                echo "::group::python version"
                python --version
                echo "::endgroup::"

                echo "tee"
                echo "::group::tee"
                tee
                echo "::endgroup::"
          - name: 下载分支
            uses: actions/checkout@v3
            with:
                fetch-depth: 1
          - name: 配置 CMake (${{ matrix.os }})
            run: cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DGBK=off -G "${{ matrix.profile }}"
          - name: 安装 LCOV (Ubuntu)
            if: matrix.os == 'ubuntu-latest'
            shell: bash
            run: |
                sudo apt-get --assume-yes install lcov
          - name: 编译
            run: cmake --build ${{github.workspace}}/build --config "${{ matrix.build_type }}" --target Tests
          - name: 运行测试
            run: |
              cd build
              make test
          - name: 输出测试日志
            run: |
                cat ./build/Testing/Temporary/LastTest.log
          - name: LCOV 数据收集
            if: matrix.os != 'macos-13'
            shell: bash
            run: |
              cd build
              lcov -c -d .. -b . -o cover.info
              genhtml -o result-html cover.info
          - name: LCOV 生成数据压缩
            if: matrix.os != 'macos-13'
            shell: bash
            run: |
              cd build
              tar -zcvf result-html.tar.gz result-html/
              echo "删除原来的文件夹"
              rm -rf result-html/
          - name: Codecov
            if: matrix.os != 'macos-13'
            uses: codecov/codecov-action@v3.1.3
            with:
              file: build/cover.info
              verbose: true
              name: test - ${{ matrix.os }} - ${{ matrix.profile }}
              fail_ci_if_error: true
          - name: 上传 Artifact
            if: always()
            uses: actions/upload-artifact@v3.1.2
            with:
                name: wooden_core-Test-${{ matrix.os }}-${{ matrix.profile }}
                path: |
                    build/
                    !build/_deps/**/*
