name: CMake Matrix Self Hosted (Test)

on:
  # push:
  #   branches: [ "master" , "dev" ]
  # pull_request:
  #   branches: [ "master" , "dev" ]
  push:
    paths:
      - .github/workflows/test-self.yml
  workflow_call:
  workflow_dispatch:

jobs:
  test:
    defaults:
      run:
        shell: cmd
    runs-on: [softer-server] 
    steps:
      - run: |
          where cmake
          exit 0
      - run: |
          echo %PATH%
          exit 0
      - run: |
          echo whoami
          exit 0